### ISSUE TITLE
Sub-Store

### ISSUE THREAD

**Issue by huang1128** [Peng-YM/Sub-Store#1]
关键词删除和关键词重命名无法使用，修改后无效果

**Comment by Peng-YM** [comment]
最新版本应该修复了

**Comment by huang1128** [comment]
9月2前可以使用，现在没效果，surge和loon全试过了，机场也换了几个试过没啥用

**Comment by Peng-YM** [comment]
更新一下脚本，我这里没有问题

**Comment by huang1128** [comment]
APP卸载过，脚本更新过，自从把国旗移动至节点操作后无用，日志显示Delete Operator" with arguments: 
 >>> ["A+中转"]

**Comment by huang1128** [comment]
换手机试过，就是没效果

**Comment by Peng-YM** [comment]
方便的话麻烦提供完整日志信息

**Comment by huang1128** [comment]
=======================================================================
06 02:26:22 [Console]   Processing subscription: buding, target platform ==> Loon.
06 02:26:22 [Console]   Initializing parsers...
06 02:26:22 [Console]   19 parser added.
06 02:26:22 [Console]   Parsers initialized.
06 02:26:22 [Console]   Applying operator "Keyword Rename Operator" with arguments: 
 >>> [{"old":"G01 HK B1[2倍]","now":"HK"}]
06 02:26:22 [Console]   Applying operator "Keyword Delete Operator" with arguments: 
 >>> ["G01"]
06 02:26:22 [Debug]   script response length:7106
06 02:26:22 [Console]   =======================================================================
06 02:26:22 [Console]   Processing subscription: leisu, target platform ==> Loon.
06 02:26:22 [Console]   Initializing parsers...
06 02:26:22 [Console]   19 parser added.
06 02:26:22 [Console]   Parsers initialized.
06 02:26:23 [Console]   Applying filter "Useless Filter" with arguments:
 >>> None
06 02:26:23 [Console]   Applying operator "Keyword Delete Operator" with arguments: 
 >>> ["A+"]
06 02:26:23 [Console]   Applying operator "Keyword Rename Operator" with arguments: 
 >>> [{"old":"2.0X","now":"10.0X"}]

**Comment by Peng-YM** [comment]
这个日志看上去没有问题，我觉得你关键词打错了，注意大小写

**Comment by huang1128** [comment]
大小写和中英文符号和复制原节点名称都试过，还是无法修改。能否给个刚开始的脚本地址，最开始是可以修改。

**Comment by Peng-YM** [comment]
问题无法重现

**Comment by Peng-YM** [comment]
先前版本和UI无法兼容，所以不建议使用旧版本。

**Comment by huang1128** [comment]
好吧，能不能在频道发起投票，收集下这些问题，我都不清楚这个问题是不是只有我使用存在
