### ISSUE TITLE
请教使用问题

### ISSUE THREAD

**Issue by dante2046** [Peng-YM/Sub-Store#10]
从组合订阅中复制的链接，
似乎并不能直接作为 surge 的external-group代理列表
是需要在连接中添加其他参数吗

**Comment by Peng-YM** [comment]
不需要的，可以直接作为外部代理列表使用。如果不能正常使用，请查阅教程并检查配置

**Comment by Peng-YM** [comment]
https://www.notion.so/Sub-Store-6259586994d34c11a4ced5c406264b46

**Comment by dante2046** [comment]
> https://www.notion.so/Sub-Store-6259586994d34c11a4ced5c406264b46

你好，经过排查，发现是有一条订阅出现问题，导致的即使该订阅独立一条也会出现无法作为外部代理列表的情形

**Comment by dante2046** [comment]
> https://www.notion.so/Sub-Store-6259586994d34c11a4ced5c406264b46

你好，经过一番排查，是我这里有一条订阅经过sub-store处理后无法正常使用，想通过私信当时寻求帮助

**Comment by Peng-YM** [comment]
可以的
