### ISSUE TITLE
surge订阅节点无法与sub-store同步

### ISSUE THREAD

**Issue by jesir000** [Peng-YM/Sub-Store#102]
sub-store上设置正常、显示正常，但是surge没有同步，多次更新外部资源也不行。

**Comment by jesir000** [comment]
![image](https://user-images.githubusercontent.com/73181101/170912807-35533004-54db-4b45-a966-4cdbe9e2ab00.jpeg)![image](https://user-images.githubusercontent.com/73181101/170912843-441d88bd-4cf7-4a17-9a68-2aa746da1498.png)![image](https://user-images.githubusercontent.com/73181101/170912866-1f7f25a5-4b5b-466e-9fca-26877a439062.jpeg)

**Comment by jesir000** [comment]
![image](https://user-images.githubusercontent.com/73181101/170914888-94adb38b-0415-4cd8-bdf9-626de4558a31.jpeg)
日志显示应该是修改成功，但是面板上没有变化

**Comment by Peng-YM** [comment]
直接浏览器访问sub-store的链接能否正常显示节点？

**Comment by jesir000** [comment]
正常显示，与设置一直

**Comment by Peng-YM** [comment]
考虑是Surge问题

**Comment by singupcc** [comment]
你是不是订阅了本地节点？我是组合订阅里含本地订阅节点，则不能在surge更新成功

**Comment by Peng-YM** [comment]
> 你是不是订阅了本地节点？我是组合订阅里含本地订阅节点，则不能在surge更新成功

还有这个问题？

**Comment by singupcc** [comment]
> > 你是不是订阅了本地节点？我是组合订阅里含本地订阅节点，则不能在surge更新成功
> 
> 还有这个问题？

可能是我个人问题吧！我复制了几个vmess节点作为本地订阅，然后组合订阅如果选择了这个节点组，在色鸡当中就没办法更新！如果组合订阅只是勾选我那几个机场，色鸡当中就可以正常更新！我也不知道为啥

**Comment by TributePaulWalker** [comment]
> 子存储上设置正常、显示正常，但surge没有同步，多次更新外部资源也不行。我也遇到这个问题
