### ISSUE TITLE
印度🇮🇳旗帜缺失

### ISSUE THREAD

**Issue by bunizao** [Peng-YM/Sub-Store#107]
印度🇮🇳旗帜缺失，印度节点匹配到海盗旗🏴‍☠️

**Comment by Peng-YM** [comment]
请提供一下节点名以排查问题

**Comment by bunizao** [comment]
> 请提供一下节点名以排查问题

我先使用了节点重命名的脚本 所以应该会对应到IN上面

**Comment by Peng-YM** [comment]
> > 请提供一下节点名以排查问题
> 
> 我先使用了节点重命名的脚本 所以应该会对应到IN上面

截图看一下节点名字

**Comment by bunizao** [comment]
> 节点

![image](https://user-images.githubusercontent.com/102936102/172413052-3bb8a695-ba48-47dd-aa62-5f5b9fd66cce.jpeg)

**Comment by Peng-YM** [comment]
已修复
