### ISSUE TITLE
转换clash订阅后无法使用

### ISSUE THREAD

**Issue by ieloug1** [Peng-YM/Sub-Store#11]
使用sub-store转换clash订阅后，在该订阅节点列表里可以看到节点，复制到浏览器打开同样可以看到节点信息。将链接导入到surge策略组的外部代理后，也可订阅出节点，但是无法ping通。

**Comment by Peng-YM** [comment]
可能是转换错误，请提供订阅文件，之后重置订阅即可

**Comment by ieloug1** [comment]
> 可能是转换错误，请提供订阅文件，之后重置订阅即可

我tg私聊给您吧

**Comment by Peng-YM** [comment]
已定位问题并修复，抱歉最近确实比较忙。

**Comment by tangjunhua1993** [comment]
我刚刚试了，surge也有这个问题，麻烦大佬看看  我用的是 surge for mac
