### ISSUE TITLE
订阅链接

### ISSUE THREAD

**Issue by Nshandeshu** [Peng-YM/Sub-Store#114]
很好用
希望能增加个，订阅链接添加**自定义host**

**Comment by Peng-YM** [comment]
请具体描述一下需求

**Comment by Nshandeshu** [comment]
> 请具体描述一下需求

修改或是添加节点的host

![1](https://user-images.githubusercontent.com/65987838/173973413-cc5313fa-720f-4a02-8006-0ee0fbf066d8.png)
![2](https://user-images.githubusercontent.com/65987838/173973417-73b4b6de-8aa4-4175-8f40-ca31a0d26e19.png)

**Comment by xream** [comment]
我多嘴一下 修改混淆其实没那么简单 可以参考下我的 但是我的也不一定对哈

https://github.com/xream/scripts/blob/main/surge/modules/sub-store-scripts/mega/index.js#L345

**Comment by Nshandeshu** [comment]
> 我多嘴一下 修改混淆其实没那么简单 可以参考下我的 但是我的也不一定对哈
> 
> https://github.com/xream/scripts/blob/main/surge/modules/sub-store-scripts/mega/index.js#L345

原来有这么多了

**Comment by Nshandeshu** [comment]
> 请具体描述一下需求

刚看到，原来作者已经做了脚本
https://raw.githubusercontent.com/Peng-YM/Sub-Store/master/scripts/vmess-ws-obfs-host.js
