### ISSUE TITLE
发生了SSL错误，无法建立与该服务器的安全连接

### ISSUE THREAD

**Issue by DuckRaiser** [Peng-YM/Sub-Store#15]
![IMG_D11F6A0C7CA1-1](https://user-images.githubusercontent.com/52232447/98434183-6e5d5f00-2108-11eb-8427-4edc284b020d.jpeg)
这个是什么情况
![image](https://user-images.githubusercontent.com/52232447/98434193-7f0dd500-2108-11eb-8248-503018713bea.png)
虽然不是特别影响使用
是我本地的问题吗

**Comment by Peng-YM** [comment]
应该是你没有配置好证书，另外需要打开VPN才能更新外部资源

**Comment by DuckRaiser** [comment]
感谢您抽空回复，要开着vpn我知道，证书我也添加且信任了。
在substore里我是把一个机场按照国家分成了六个单独的订阅 会不会是因为一次性更新的话，都是访问的一个订阅地址被限制了。因为我是六个substore订阅中间会有两三个会出现SSL错误。

**Comment by Peng-YM** [comment]
我同时更新5个没有出现问题哦
