### ISSUE TITLE
同云步功能好像不能用了

### ISSUE THREAD

**Issue by BitionSong** [Peng-YM/Sub-Store#16]
昨晚突然被覆盖了之前得配置！现在改了手动也没法上传也不能下载！但是重启后又会被覆盖之前的配置，不能正常使用了！

**Comment by Peng-YM** [comment]
检查一下网络问题，我这里仍然可以用的

**Comment by BitionSong** [comment]
> 检查一下网络问题，我这里仍然可以用的

网络都正常的，修改配置都可以保存成功的！我在看看！之前也没修改过东西

**Comment by BitionSong** [comment]
![Uploading A00B0CA0-4EEA-470D-BB76-953326AEEE7F.png…]()

**Comment by BitionSong** [comment]
> 检查一下网络问题，我这里仍然可以用的

![Uploading 5AB21A53-E808-4885-A5C2-FA4C9F3E68B9.png…]()

**Comment by BitionSong** [comment]
商店版可备份，tf版本不行。。。。。。
