### ISSUE TITLE
Surge（4.10.0）1847

### ISSUE THREAD

**Issue by LisonChan** [Peng-YM/Sub-Store#18]
更新后iOS设备上Surge版无法使用，Mac上的Surge倒是可以正常使用，使用相同的配置，iOS上貌似MitM失败了，但是MitM其他主机名表现正常

**Comment by LisonChan** [comment]
日志里一直提醒
<WARNING> [SGJSVM] [Sub-Store] An exception was catched while evaluate script Sub-Store: TypeError: Attempted to assign to readonly property.. Line number 2, column: 36331

**Comment by Peng-YM** [comment]
能否提供订阅供排查？

**Comment by Jiaowoz** [comment]
![2E264EB6-73F0-4354-A95D-65EAE796D01D](https://user-images.githubusercontent.com/16634459/100193719-4e62d380-2f2f-11eb-8ac9-ee66b687275e.png)
我也这样

**Comment by Jiaowoz** [comment]
> 能否提供订阅供排查？

订阅指的是哪个，机场订阅吗？

**Comment by Peng-YM** [comment]
问题已经解决，请运行以下脚本
```js
$persistentStore.write(null, "sub-store");
$done();
```
在Loon或者QX更新脚本之后再上传一次gist。之后云同步功能即可修复。
