### ISSUE TITLE
请问订阅是否不支持BASE64加密后的内容

### ISSUE THREAD

**Issue by qhq** [Peng-YM/Sub-Store#20]
订阅链接直接打开是一串BASE64加密后的内容，添加订阅刷新不出内容或报错。

**Comment by Peng-YM** [comment]
支持的呀，麻烦提供一下订阅供排查问题。

**Comment by qhq** [comment]
我试了下有的是支持的，我朋友给我这个就不行。连接没办法提供了，我把解密的密码改了再加你回来的内容贴一下。
`c3NyOi8vTVRBeExqTXlMak16TGpFeE5Eb3lNemN6TnpRNllYVjBhRjl6YUdFeFgzWTBPbUZsY3kweU5UWXRZMlppT25Cc1lXbHVPbFJ1VG5CaFIxWndaRWQzTjFsVVJuQmtWMnd6T0RJM01pWXlVMVJPZG1OSFZUVk5aeTgvYjJKbWMzQmhjbUZ0UFNaeVpXMWhjbXR6UFZORmN5Wm5jbTkxY0QxV1JtYz0gc3NyOi8vTVRRMExqSXdNaTR5TXk0eU5UTTZNalUxTXpZNllYVjBhRjl6YUdFeFgzWTBPbUZsY3kweU5UWXRZMlppT25Cc1lXbHVPbFJxUm5waFIxWjFXak5KZUVzeWQzcGlSRkV4VFcwNE4yRnFSblZrUkVab1lqTXBMaUYxYzJoa2FXUnBjMmhrYVdsamJtTnBkemd5THo5dlltWnpjR0Z5WVcwOUpuSmxiV0Z5YTNNOVZsWk5KbWR5YjNWd1BWWkdadz09 `

**Comment by qhq** [comment]
另外这个代理池的格式也添加不了好像，qx里可以直接识别用的
https://proxypoolss.tk/clash/proxies

**Comment by qhq** [comment]
> 另外这个代理池的格式也添加不了好像，qx里可以直接识别用的
> https://proxypoolss.tk/clash/proxies

这个可能是数据太多超时了好像
