### ISSUE TITLE
关于正则重命名

### ISSUE THREAD

**Issue by BaileyZyp** [Peng-YM/Sub-Store#22]
想问下作者正则重命名后面想修改的名字怎么加序号

比如说我的表达式为 ([A-Z]|[a-z]).*HK 想修改为HK 01、HK 02以此类推

> 想达到的效果

节点名称
D+.ZV231353丨V2RAY.电联特批 HK
D+.ZV231353丨V2RAY.三網特批 HK

想修改为
HK 01
HK 02

**Comment by Peng-YM** [comment]
一种通用的办法是暴力重命名再加上序号：
```
^.*HK.*$   ==>  HK
```

序号可以通过脚本操作添加，具体请看https://www.notion.so/889b5abb19eb441f8871b3c4362e7df6
