### ISSUE TITLE
自建Node后端，需求自动更新订阅、上传gist功能。

### ISSUE THREAD

**Issue by primovist** [Peng-YM/Sub-Store#239]
自建在群晖用pm2起的后端，现在仅可手动刷新订阅、上传gist，可否更新一个功能，使其自动化。感谢！

**Comment by how1ewu** [comment]
同问，自定义部署无法自动更新

**Comment by how1ewu** [comment]
> 自建在群晖用pm2起的后端，现在仅可手动刷新订阅、上传gist，可否更新一个功能，使其自动化。感谢！

有一个解决办法，通过发包进行订阅，配置一个自动执行脚本例如cron之类的，后端地址/api/sync/artifacts

**Comment by xream** [comment]
🆕 新增 定时任务
时区 `Asia/Shanghai`
日志在 `cron.log`

我维护的 Docker 版 https://hub.docker.com/r/xream/sub-store
