### ISSUE TITLE
“发生错误，无法创建订阅”

### ISSUE THREAD

**Issue by stefaneliu** [Peng-YM/Sub-Store#24]
我按照指南在surge中输入地址安装了模块并打开了surge，然后输入网址，到这里一切正常。
但是当我输入订阅名称和订阅链接后，按下下载键，屏幕底部就出现标题中提到的红字。
iphone，ipad，mac各个平台上的surge都试过了，手头的几个机场（包括my，pq等）也都试过了，都是一样的结果。
不明白是什么原因，surge的版本是最新的tf版4.10.0-1850，本身运行正常，可以正常走代理的。是否可帮忙指点一二，谢谢。

**Comment by centvir** [comment]
遇到同样的问题

**Comment by Peng-YM** [comment]
Loon和Surge执行
```
$persistentStore.write(null, "sub-store")
$done()
```js

QX执行
```js
$prefs.setValueForKey("{}",  "sub-store")
```

**Comment by stefaneliu** [comment]
> 尝试重建缓存
> Loon和Surge执行
> 
> ```js
> $persistentStore.write(null, "sub-store")
> $done()
> ```
> 
> QX执行
> 
> ```js
> $prefs.setValueForKey("{}",  "sub-store")
> ```

不是很懂，请问surge在什么地方执行这段代码？脚本编辑器吗？还有如何重建缓存？谢谢。

**Comment by Peng-YM** [comment]
就是脚本编辑器执行

**Comment by stefaneliu** [comment]
> 就是脚本编辑器执行

我通过脚本编辑器执行该段代码后，返回结果是：
Result:
Null

执行后再新建订阅，还是相同的结果，问题并没有解决。。。

**Comment by Peng-YM** [comment]
创建订阅之后提供详细的最近请求截图。

**Comment by stefaneliu** [comment]
> 创建订阅之后提供详细的最近请求截图。

https://sm.ms/image/kl5Te27FMq4UXbj

https://sm.ms/image/ZqnIJLF1T7vWBSy

如图，谢谢

**Comment by Peng-YM** [comment]
请检查你的模块有没有安装好，脚本和MITM有没有打开。从图上看，你的脚本没有触发。正常状态应该类似这样![image](https://user-images.githubusercontent.com/21050064/101849270-5313c280-3b92-11eb-90a0-fd207ca780ca.png)

**Comment by stefaneliu** [comment]
多谢，已搞定，是因为没有打开mitm而导致的。
