### ISSUE TITLE
最近数据同步的时间错误

### ISSUE THREAD

**Issue by LisonChan** [Peng-YM/Sub-Store#27]
js已更新到最新版，Surge版本也是最新版本，Safari为最新系统最新版本；尝试过删除gist上的文件再次上传无法解决，尝试过运行清除缓存的脚本后也无法解决，尝试过清除浏览器的缓存也无法解决。但是感觉也不太影响使用

**Comment by Peng-YM** [comment]
无法复现

**Comment by LisonChan** [comment]
最新的一次js更新后已经正常
