### ISSUE TITLE
【建议&求助】release分支cdn加速链接

### ISSUE THREAD

**Issue by makaspacex** [Peng-YM/Sub-Store#290]
想使用jsdelivr加速，发现固定链接无法链接到最新的release(也许是我没找对方法)，可否新建一个release分支，将assets文件推送到release分支上，这样就能通过固定链接访问最新的文件了。

**Comment by xream** [comment]
感觉意义不大 但是加了 https://github.com/sub-store-org/Sub-Store/tree/release
