### ISSUE TITLE
发生错误，无法保存订阅

### ISSUE THREAD

**Issue by pompeyY** [Peng-YM/Sub-Store#3]
用的surge，机场订阅链接里面是v2ray的节点,已查看官方教程，节点操作没有任何问题，但是保存的时候报 发生错误，无法保存订阅。是不是不支持该订阅格式，，，这个订阅地址小火箭可以直接订阅，中转网站也可以转换成功，我直接打开订阅链接貌似是用base64编码了，这种情况怎么解哈（是不是必须用surge专用的订阅链接才能在sub-store里面转给surge用？）

**Comment by pompeyY** [comment]
我用base64加密一次之后是这种

**Comment by pompeyY** [comment]
vmess://xxxxxxxxx

**Comment by pompeyY** [comment]
vmess://后面的又用base64编码了一下

**Comment by Peng-YM** [comment]
无法保存订阅不是解析问题，应该是没有配置好。目前只有TF版软件才能使用
