### ISSUE TITLE
Bug提交

### ISSUE THREAD

**Issue by ftnice** [Peng-YM/Sub-Store#30]
Surge的外部资源-全部更新，如果Sub-Store有一个资源是空的，就是不含有效节点，那么其它正常的Sub-Store资源也会导致更新失败
![B7F79177-899E-47F0-A080-E2FA0410ABF4](https://user-images.githubusercontent.com/61619763/104995577-7e2ae500-5a61-11eb-95b3-68f2402be004.jpeg)

手动更新正常的节点可以更新出来
![7D0B5EB3-ED0C-44DF-AE51-FB825217FAAF](https://user-images.githubusercontent.com/61619763/104995708-aca8c000-5a61-11eb-843d-48f09bfb62eb.jpeg)

**Comment by ftnice** [comment]
就是这样的通知会产生
![F6FF086D-2006-4316-8277-C7211F80A98E](https://user-images.githubusercontent.com/61619763/105008855-c1428380-5a74-11eb-92f7-d5d1c6d8365c.jpeg)

**Comment by Peng-YM** [comment]
有时间看看，按理来说不同订阅应该不会互相影响的
