### ISSUE TITLE
iPhone上surge(1873)无法上传或者恢复云端配置

### ISSUE THREAD

**Issue by shwsh** [Peng-YM/Sub-Store#32]
在最新的surge1873版本上我更改了我的sub-store内容后想要上传到github上，发现提示error:network Error错误。
我怀疑是我的问题，在MacBook上进行操作试图复现发现MacBook上的sub-store可以正常修改并上传，我在我的iPad端也可以成功的将我修改后的配置从github上下载。但是在我尝试iPhone仍提示network error错误。
我先后尝试清除sub-store缓存，更换为商店版surge，更换网络后依旧没有任何改变
o(╥﹏╥)o。
我再三确认我的mitim已打开，网络正常。我的iPhone设备为iPhone8plus，系统为ios最新，js也更新最新版本。
同时我在qx上第一次使用substore可以还原。![image](https://user-images.githubusercontent.com/59083195/106184580-b3ab9d00-61dc-11eb-8d5c-98c7f0c70aa2.jpeg)

**Comment by Peng-YM** [comment]
Network Error应该是无法访问gist导致的。请检查：
1. 能否正常访问gist。
2. 是否存在github相关的重定向和MITM。是的话可能是错误重定向或者MITM返回了错误的结果。

**Comment by Peng-YM** [comment]
在我所有设备上均正常工作，请确认自己的配置
