### ISSUE TITLE
关于gist的安全性探讨

### ISSUE THREAD

**Issue by Asakushen** [Peng-YM/Sub-Store#325]
我在使用gist同步时发现了gist的链接形如：
`https://gist.githubusercontent.com/USERNAME/XXXXXXXXXXXXXXXXXXXX/raw/NAME`
如果手动删除后面的/raw/NAME，将能直接打开所有由Sub-Store创建的订阅链接，这是否存在安全性问题？

我有时候会分享一些订阅链接给别人，我本意是使用Sub-Store有意的创建不同的订阅分组，如此一来，是否会存在分享时，被他人获取到整个订阅的风险？

能否采取其他方式，比如将每个订阅的类似于密钥token的XXXXXXXXX这部分变得不一样（目测似乎创建不同的“仓库”即可实现）

希望作者大大考虑一下

或者是否有其他办法能更安全的分享订阅链接（还要能保持更新），希望大家一起探讨一下

**Comment by xream** [comment]
有个不那么优雅的方法: 加一个脚本操作, 在里面把内容传到另一个 gist

```
async function operator(proxies = []) {
  const GITHUB_TOKEN = ''
  const GIST_NAME = 'share'
  const FILENAME = 'mihomo.yaml'
  const platform = 'ClashMeta'

  const $ = $substore

  const { isLoon, isSurge } = $.env

  let files = {}

  let content = await produceArtifact({
    type: 'subscription',
    subscription: {},
    content: 'proxies:\n' + proxies.map((proxy) => '  - ' + JSON.stringify(proxy) + '\n').join(''),
    platform,
  })


  const manager = new ProxyUtils.Gist({
      token: GITHUB_TOKEN,
      key: GIST_NAME,
  });

  files[encodeURIComponent(FILENAME)] = {
      content,
  };

  const res = await manager.upload(files);
  let body = {};
  try {
      body = JSON.parse(res.body);
      // eslint-disable-next-line no-empty
  } catch (e) {}

  // console.log(JSON.stringify(body, null, 2))

  const raw_url = body.files[encodeURIComponent(FILENAME)]?.raw_url;
  console.log(raw_url)
  const new_url = raw_url?.replace(/\/raw\/[^/]*\/(.*)/, '/raw/$1');
  
  console.log(new_url)
  if (isSurge) {
    $notification.post(`🌍 Sub-Store`, 'Gist', `点击复制 ${new_url}`, {
      action: 'clipboard',
      text: new_url
    })
  } else {
    $.notify('🌍 Sub-Store', `Gist: ${new_url}`)
  }
  
  
  return proxies
}
```

**Comment by xream** [comment]
@Asakushen 改动有点大 应该暂时不会加

**Comment by xream** [comment]
整理成了单独的脚本 方便使用

https://t.me/zhetengsha/1428

▎使用场景

1. 单独分享到另一个 Gist, 与自己的 Gist 隔离. 分享给亲朋好友们

2. 可传入不同的 token, 实现上传至其他账号的 Gist

▎说明

具体说明可查看脚本内容

常用参数:

`name` Gist 名称. 为防止意外修改你已有的 Gist, 此参数为必填
`file` 文件名. 为防止意外修改你已有的 Gist 文件, 此参数为必填
`token` GitHub Token. 默认为 Sub-Store 中已经配置的 Token
`target` 指定输出的目标. 默认为 ClashMeta

节点操作 -> 脚本操作  -> 填入链接: `https://raw.githubusercontent.com/xream/scripts/main/surge/modules/sub-store-scripts/upload/gist.js#name=share&file=mihomo.yaml`
