### ISSUE TITLE
Surge 显示解析订阅地址失败

### ISSUE THREAD

**Issue by wdkGitHub** [Peng-YM/Sub-Store#332]
URL : https://sub.store/download/shadowrocket?target=Surge
 
<img width="1134" alt="image" src="https://github.com/sub-store-org/Sub-Store/assets/12813051/3991d43b-2066-4774-bfe5-2e62c7c3a267">
<img width="495" alt="image" src="https://github.com/sub-store-org/Sub-Store/assets/12813051/502fc7db-bf5d-4bd0-a796-65635ff97733">

Surge for mac 5.7.4

**Comment by xream** [comment]
没看懂你想表达什么. 盲猜你把订阅当成配置文件导入了.
