### ISSUE TITLE
vmess + ws 节点解析异常

### ISSUE THREAD

**Issue by imbalaomao** [Peng-YM/Sub-Store#337]
原订阅导入Clash Verge Rev后显示如下：
```yaml
- { name: 🇭🇰香港, type: vmess, server: a.b.c.d, port: 443, uuid: 这是一个UUID, alterId: 0, cipher: auto, udp: true, network: ws }
```

但是将订阅加入Sub-Store，且使用了**旗帜操作**、脚本操作 `$server.name = '[机场名] ' + $server.name`，并以**Clash-Meta格式**或**通用格式**导入之后，发现配置会改变为以下内容：
```yaml
- {"name":"[机场名] 🇭🇰 香港","type":"vmess","server":"a.b.c.d","port":443,"cipher":"auto","uuid":"这是一个UUID","alterId":0,"tls":false}
```

可见，原本 vmess + ws 的格式变成了 vmess + tcp 的格式，导致节点无法正常连接。

**Comment by xream** [comment]
<img width="341" alt="image" src="https://github.com/sub-store-org/Sub-Store/assets/1210282/80b3fe64-912c-4617-89da-ff22a5e88ab4">
如图导出私发我看看
