### ISSUE TITLE
Surge For Mac无法通过cron-sync-artifacts.js脚本自动更新远程订阅到gist

### ISSUE THREAD

**Issue by nichwang88** [Peng-YM/Sub-Store#37]
感谢作者发布自动同步脚本，我在Surge iphone端和Mac端同时配置了Sub Store，并同时设置了同步脚本。(由于我的配置是通过icloud共享的，所以脚本也是iphone端和mac端同时响应，我其他的脚本都能正常运行。)
iphone端正常每日中午12点能自动更新订阅。
但是很遗憾，Mac端没法自动同步，而且成功或者不成功都没有任何通知，不知作者能帮忙看下这是什么原因，多谢。

**Comment by nichwang88** [comment]
查看脚本后使用 https://sub.store/api/cron/sync-artifacts 在浏览器运行。MacOS端返回：
`{"success":[],"failed":[{"name":"surge","type":"subscription","source":"bityun","platform":"Surge","updated":1614777090645,"url":"https://gist.githubusercontent.com/nichwang88/**********************************************/raw/surge","sync":true}]}`

通知显示：同步订阅失败，原因： Socket closed by remote peer。

iPhone端返回正常：
`{"success":[{"name":"surge","type":"subscription","source":"bityun","platform":"Surge","updated":1614777529439,"url":"https://gist.githubusercontent.com/nichwang88/**********************************************/raw/surge","sync":true}],"failed":[]}`

**Comment by Peng-YM** [comment]
Mac OS端的sub-store有没有配置？我指的是github token之类的

**Comment by nichwang88** [comment]
和iphone端配置一样的Token，并且能和iphone一样，能在数据同步那块上传和恢复。
而且我有两台macos，一台imac、一台macbook，都安装有Surge for Mac，问题一样。

**Comment by Peng-YM** [comment]
Socket closed by remote peer
这个错误是你网络的问题，请切换全局代理试试

**Comment by Peng-YM** [comment]
在我自己的Mac上完全正常

**Comment by nichwang88** [comment]
还真是在全局上能用，再切换回规则判断也可以了，这是怎么回事？难倒我规则有问题？但是我手机正常的啊

**Comment by nichwang88** [comment]
我刚刚测试浏览器运行https://sub.store/api/cron/sync-artifacts，可以同步。
但是切换到cron-sync-artifacts.js脚本，依然不能同步，无论全局还是规则判断。

**Comment by Peng-YM** [comment]
经过几次测试，发现这是Surge for Mac的问题。
Surge for Mac脚本请求不经过重写，因此不触发sub-store更新。

**Comment by Peng-YM** [comment]
暂时无解，只能等官方更新了。

**Comment by nichwang88** [comment]
这情况就太专业，我也没搞清，方便的话，您是否可以向官方反馈，多谢。
您这功能确实非常不错，赞一个。至少iphone一切正常。

**Comment by nichwang88** [comment]
不知为何，iOS段目前也不能通过脚本同步了。
系统14.5.1
surge ios 版本 4.7.0
