### ISSUE TITLE
[bug v2.14.424] UA默认指定成了"clash", 而不是用户设置的

### ISSUE THREAD

**Issue by augumn** [Peng-YM/Sub-Store#375]
最新版本2.14.424 请求ua似乎有个bug, 通过抓包发现发出请求订阅的为"clash", 而不是我自己填的"clash-verge/v1.7.7", 不能获取到订阅

```
User-Agent: clash
```
![image](https://github.com/user-attachments/assets/6a3f1a36-caa0-4980-92c7-1863fadbbd57)

背景:
有的机场会校验ua才下发订阅, 更新成2.14.424之后不能获取某个机场的订阅, 在更新到2.14.424以前是正常的, 所以怀疑是否是新版本的bug

**Comment by xream** [comment]
1. 你看到的是查询订阅流量信息的请求
2. 默认查询流量信息的 `User-Agent` 从 `Quantumult%20X/1.0.30 (iPhone14,2; iOS 15.6)` 改为 `clash`

如需修改订阅查询流量信息时的 `User-Agent`,
例如继续使用 QX 的:
如图 
![image](https://github.com/user-attachments/assets/372381cd-6d36-41d0-bdc7-bc1996eef3e2)

`#flowUserAgent=Quantumult%2520X%2F1.0.30%20(iPhone14%2C2%3B%20iOS%2015.6)`

**Comment by CMJNB** [comment]
<img width="1059" height="808" alt="Image" src="https://github.com/user-attachments/assets/7f18456b-663b-424d-87ca-8244cad76d5d" />

查询流量的ua能用全局的吗？有点强迫症🫣。。主要是看机场的订阅记录来区分使用者。

**Comment by xream** [comment]
@CMJNB 因为改 flowUserAgent 属于低频操作, 所以之前没有单开一个全局 flowUserAgent. 但其实后端已经接了. 如果你一定想设个全局的 flowUserAgent 的话, 可以自己设置 settings 数据, 字段为 `defaultFlowUserAgent`, 跟 `defaultUserAgent` 同一层级. 或者你等我下个版本发, 我加个可在前端设置.

**Comment by CMJNB** [comment]
> [@CMJNB](https://github.com/CMJNB) 因为改 flowUserAgent 属于低频操作, 所以之前没有单开一个全局 flowUserAgent. 但其实后端已经接了. 如果你一定想设个全局的 flowUserAgent 的话, 可以自己设置 settings 数据, 字段为 `defaultFlowUserAgent`, 跟 `defaultUserAgent` 同一层级. 或者你等我下个版本发, 我加个可在前端设置.

@xream 谢谢，舒服了

**Comment by xream** [comment]
@CMJNB 前端: 2.16.65 已更新支持设置默认 flowUserAgent
