### ISSUE TITLE
iPhone Surge配置了你提供的模块，但是sub-store里面提示无法拉取和无法获取

### ISSUE THREAD

**Issue by johnsonmoment24** [Peng-YM/Sub-Store#38]
iPhone Surge配置了你提供的模块，但是sub-store里面提示无法拉取和无法获取。之前一直好好的，现在突然不行的

**Comment by Peng-YM** [comment]
检查Surge配置：
1. MITM有没有打开
2. 脚本有没有启用
3. 模块有没有启用

**Comment by johnsonmoment24** [comment]
> 检查Surge配置：
> 
> 1. MITM有没有打开
> 
> 2. 脚本有没有启用
> 
> 3. 模块有没有启用

都启用了还是不行的，结果现在发现了有兼容模式还开着TUN Only，我把它禁用了就正常了，谢谢哈
