### ISSUE TITLE
关于定时同步至gist更进一步的想法探讨

### ISSUE THREAD

**Issue by augumn** [Peng-YM/Sub-Store#393]
Sub-Store定时同步至gist是个非常好的功能, 可能其用处可以超出机场线路订阅这一个范围。

起初有这个想法是我自己维护了一套m3u8源，这个源有个问题是播放链接带时间戳和签名校验，我需要通过程序去定时更新链接时间戳和签名，然后生成新的m3u8文件。如果我想在各个设备上使用这套源，包括在户外的时候，我可以把它上传到gist上去，但是麻烦的点就在于我每次都在手动导出m3u8文件，再手动上传到github gist上。

```m3u8
#EXTINF:-1,S01E01
https://www.baidu.com/1d965f0e52b67d4d30b7a37235e60688-ld.mp4?sign=9defe2dccfb2ab091ee65aaa682b3561&t=676bdb64&clientType=ios_pttv
#EXTINF:-1,S01E02
https://www.baidu.com/1d965f0e52b67d4d30b7a37235e60688-ld.mp4?sign=9defe2dccfb2ab091ee65aaa682b3561&t=676bdb64&clientType=ios_pttv

```

然后想到了Sub-Store的定时同步功能，假设我在本地电脑上起了一个任意的服务，比如地址是“http://192.168.1.100:8888/videos.m3u8”, 同时Sub-Store支持固定请求一个地址，然后连同订阅一起原样将指定的文件上传到订阅链接的gist仓库，这样就更进一步的扩展了Sub-Store的应用范围。

当然可能并不是这么简单的实现了，但是确实有这样的一种可能性，拿出来探讨探讨。

**Comment by xream** [comment]
"文件" 功能完全可以实现你这个需求
