### ISSUE TITLE
经 Sub-Store 处理后，节点配置发生错误，导致无法连接

### ISSUE THREAD

**Issue by Martian746** [Peng-YM/Sub-Store#45]
问题订阅获取的节点（共1个 SS 节点，A）配置经 Sub-Store 处理后，密码末尾的 `=` 丢失，导致节点无法连接。

问题订阅的 Sub-Store 具体配置：
1. `订阅` → `单个订阅` → `常用选项` 全部默认选项，`节点操作` 无；
2. 用了组合订阅。但同样 `常用选项` 全部默认选项，`节点操作` 无；
3. 最终从组合订阅获取的 SS 节点 A，`password` 末尾的 `=` 丢失，导致该节点无法连接。

相关订阅连接已 Telegram 私信。

**Comment by Peng-YM** [comment]
password 中不应该包含 “=”，目前 sub-store 认为此类节点是非法的
