### ISSUE TITLE
给出一个Surge无法使用脚本自动同步的解决方案

### ISSUE THREAD

**Issue by nazocthun** [Peng-YM/Sub-Store#46]
使用快捷指令，配置如下，配置好自动化之后，可每天自动同步。
实测15天+无错误
![配置图片](https://i.loli.net/2021/08/13/7GDAyprBW4QUcPn.jpg)

**Comment by Peng-YM** [comment]
是的，我之前也是这么用的。欢迎分享快捷指令～

**Comment by nazocthun** [comment]
我目前自己使用的，有需要可以拿去使用，需要手动配置自动化。
https://www.icloud.com/shortcuts/cfe17d8ef9ab44b2b7ab1bc7be30efa3

**Comment by Peng-YM** [comment]
感谢分享，晚上发到群里～

**Comment by nichwang88** [comment]
感谢分享，这个方法确实不错，解决了我的同步难题。

**Comment by Skyxim** [comment]
Loon也没法mitm脚本内部发起的请求，所以也需要使用此脚本，qx快捷指令算了

**Comment by llity** [comment]
> 是的，我之前也是这么用的。欢迎分享快捷指令～

现在可以使用模块同步了吗？谢谢

**Comment by llity** [comment]
> > > 是的，我之前也是这么用的。欢迎分享快捷指令～
> > 
> > 
> > 现在可以使用模块同步了吗？谢谢
> 
> 模块同步具体是指？
这是JS的方法有效吗？还有能自动备份吧。
https://raw.githubusercontent.com/Peng-YM/Sub-Store/master/scripts/cron-sync-artifacts.js

**Comment by Peng-YM** [comment]
> 模块同步具体是指？ 这是JS的方法有效吗？还有能自动备份吧。 https://raw.githubusercontent.com/Peng-YM/Sub-Store/master/scripts/cron-sync-artifacts.js

这个脚本已经失效了，请使用上面的捷径代替～

**Comment by lyxhwy** [comment]
现在还能用吗
