### ISSUE TITLE
Sub-Store 建议

### ISSUE THREAD

**Issue by GmomotdlyH** [Peng-YM/Sub-Store#5]
大佬能否将本地转换后的节点列表也可以同步到gist，这样PC端的订阅就可以直接填自己的gist库地址了。。。

**Comment by Peng-YM** [comment]
节点列表是动态生成的，这样才能保证每次获取都时候都是最新的信息。

**Comment by GmomotdlyH** [comment]
好吧，感谢回复。

**Comment by shangrenxi** [comment]


> 节点列表是动态生成的，这样才能保证每次获取节点的时候都是最新的信息。

需要更新的时候在store上重新生成下，然后上传到 gist不更香吗？我也想要这个功能
