### ISSUE TITLE
The subscription link does not support vmess?

### ISSUE THREAD

**Issue by Dnnecessary** [Peng-YM/Sub-Store#50]
Version: 2.1.11(306)

新增单个订阅，订阅链接内输入 vmess 链接， 提示我： 订阅链接不合法。
搭建的是 V2Ray

**Comment by Peng-YM** [comment]
直接输入 vmess 链接是非法的，Sub-Store 中目前只允许输入订阅链接。
一个可行的办法是把 vmess 链接放入 gist 中，再使用 Sub-Store 转换
