### ISSUE TITLE
Clash 格式Vmess节点解析错误

### ISSUE THREAD

**Issue by Skyxim** [Peng-YM/Sub-Store#51]
\- {name: 🇺🇸 US-VMESS, server: host, port: 8080, type: vmess, uuid: uuid, alterId: 0, cipher: aes-128-gcm, tls: false, network: ws, ws-path: /, udp: true}

这个格式使用vmess+ws，不用tls，通过sub-store丢失了path，变成如下（qx下测试）：
vmess=host:8080, method=aes-128-gcm, password=uuid, fast-open=true, udp-relay=true, tag=🇺🇸 US-VMESS

KOP-XIAO的解析器能正确解析并使用

有尝试使用subconverter先转换成loon或qx的格式，放入sub-store可以成功使用节点，subconverter转成clash导入无法使用，也是丢失了path相关信息
* 通过转换subc转成qx/loon后导入由sub-store在qx中订阅得到结果：
vmess=host:8080, method=aes-128-gcm, password=uuid, obfs=ws, obfs-host=us.skyxim.com, obfs-uri=/, fast-open=false, udp-relay=false, tag=🇺🇸 US-VMESS

**Comment by Peng-YM** [comment]
Clash 格式最近似乎更新了，有时间看看 KOP-XIAO 的实现

**Comment by Peng-YM** [comment]
在这个[版本](https://github.com/Peng-YM/Sub-Store/commit/090b1cd55722902f8f4436ac81b73b9dd8e57a49)中完全重构了 YAML 解析器，现在应该能支持所有 Clash 格式了
