### ISSUE TITLE
添加支持openclash?

### ISSUE THREAD

**Issue by cicai1631** [Peng-YM/Sub-Store#63]
软路由上的clash支持下吧?

**Comment by loohalh** [comment]
> 软路由上的clash支持下吧?

大佬求指导，通过 Gist 导出是怎么弄的

**Comment by Peng-YM** [comment]
1. 生成 Gist Token，在 sub-store 设置界面填入
2. 在订阅同步页面创建并上传订阅
3. 复制定义链接粘贴到 Clash 里面
