### ISSUE TITLE
【已解决】数据同步一直失败

### ISSUE THREAD

**Issue by chaizia** [Peng-YM/Sub-Store#64]
按照教程提示申请了token，但是一直提示“备份失败!Error:Request failed with status code 500”

**Comment by singupcc** [comment]
申请的时候，相应的项目认不认识都够选上应该就可以了

**Comment by chaizia** [comment]
> 申请的时候，相应的项目认不认识都够选上应该就可以了

token的权限我都全选了的。。。请问你成功了么？

**Comment by singupcc** [comment]
很成功

**Comment by chaizia** [comment]
> 很成功

我新申请了个GitHub账号，居然也成功了。。。看来本号不能干这事。。
