### ISSUE TITLE
Surge格式Trojan协议解析错误

### ISSUE THREAD

**Issue by BlueGrave** [Peng-YM/Sub-Store#67]
最近机场更换成Trojan协议了，新的原节点信息为：
trojan://XXXX-XXXX-XXXXX-XX@xxxx.xxxx.xxx:11111?allowInsecure=1&peer=xxxxxxx.com#XXXXXXXXXXXXXXXXX
格式转换后丢失了peer信息，导致节点无法使用
我查看了源码，貌似在读取Trojan类型URL的时候获取的是sni，而不是peer

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by NobyDa** [comment]
许多trojan客户端并不认peer参数而只认sni，查了下peer关键字似乎是shadowrocket订阅的专有参数，而非trojan标准的url scheme格式。

**Comment by NobyDa** [comment]
可以试试使用clash或qx的订阅去解析，而不是使用shadowrocket订阅。

**Comment by Peng-YM** [comment]
目前对于 Trojan URL 解析采用的是 [Trojan Go](https://p4gefau1t.github.io/trojan-go/developer/url/) 的草案，因为官方没有提供标准的格式。可以按照野比大佬的建议使用 QX、Surge、Clash 解析。
