### ISSUE TITLE
不能解析clash的链接和.ymal格式的链接

### ISSUE THREAD

**Issue by Fubro** [Peng-YM/Sub-Store#68]
在loon中解析不了，如图，圈x中解析出节点

**Comment by Peng-YM** [comment]
请详细描述一下遇到的问题

**Comment by Fubro** [comment]
> 请详细描述一下遇到的问题

![image](https://user-images.githubusercontent.com/97432491/149245729-b3d318e0-3124-4f57-aa19-2c7c61ef257e.png)
![image](https://user-images.githubusercontent.com/97432491/149245798-edcb1cfd-6c50-47db-aba4-df290b2ffa9e.png)
类似这种情况，会导致loon闪退，而且解析不出来节点

**Comment by Fubro** [comment]
> 请详细描述一下遇到的问题

而且我不能同步到github，提示code500
![image](https://user-images.githubusercontent.com/97432491/149246106-673c7002-1682-4c02-b284-33011b50fc67.png)

**Comment by Peng-YM** [comment]
抱歉春节太忙，没能及时回复，能否私聊提供一下配置？
