### ISSUE TITLE
请问可以增加Surge mptcp=true参数吗？

### ISSUE THREAD

**Issue by SebastianMMC** [Peng-YM/Sub-Store#71]
请问可以增加Surge mptcp和ip-version参数吗？
https://manual.nssurge.com/policy/parameters.html

**Comment by Peng-YM** [comment]
请问 Network Framework 是不是已经被取消了？

**Comment by oldzhg** [comment]
@Peng-YM 找了一下，确实已经被暂时取消了

![51E97951-4913-4564-A645-A6A2CE344AB3_1_102_o](https://user-images.githubusercontent.com/30204608/157877155-960a0041-6515-4e28-9a33-2ab2a9253d3d.jpeg)

**Comment by Peng-YM** [comment]
那我暂时 close 掉这个 issue，后续如果这个 API 稳定了再重新 open 哈
