### ISSUE TITLE
vmess://xxxxx 节点无法转换

### ISSUE THREAD

**Issue by loohalh** [Peng-YM/Sub-Store#72]
vmess://xxxxx 节点转换时，提示订阅链接不合法，有办法转换这种链接吗
<img width="353" alt="image" src="https://user-images.githubusercontent.com/16890588/152941205-63a7d46a-12a8-437c-9e79-cd4b580be04a.png">

**Comment by Peng-YM** [comment]
这种链接并非订阅链接，因此 sub-store 不做处理

一种解决方法是把这段配置放在 gist 里面，然后在 sub-store 使用 gist 的链接即可

**Comment by loohalh** [comment]
谢谢大佬回复，但是还是想请教下gist是什么，搜了一圈还是不知道，😄

**Comment by loohalh** [comment]
> 这种链接并非订阅链接，因此 sub-store 不做处理
> 
> 一种解决方法是把这段配置放在 gist 里面，然后在 sub-store 使用 gist 的链接即可


谢谢大佬回复，但是还是想请教下gist是什么，搜了一圈还是不知道，
