### ISSUE TITLE
关于clash profile里的trojan节点转换为surge profile - sni未能正确转换

### ISSUE THREAD

**Issue by sanziliu** [Peng-YM/Sub-Store#73]
如题。

clash profile里的trojan节点转换为surge profile后，sni未能正确继承clash里的设置，而自动变更为服务器地址。因为之前一直使用vmess节点从未有过问题，这两天使用trojan节点才发现这个问题。手动更改sni到正确设置，surge可以正常使用。

不清楚是不是自己哪儿有疏忽，转换都是使用“默认”。

谢谢。

**Comment by Peng-YM** [comment]
能提供一段配置截图吗，关键信息脱敏即可？
- 原始 Clash 配置截图
- 转换后 Surge 配置截图

**Comment by sanziliu** [comment]
你好，多谢迅速回复。

附图为clash和surge profile的具体截图，供参考，谢谢。

Feng

From: Peng-YM ***@***.***>
Date: Wednesday, February 9, 2022 at 10:30 AM
To: Peng-YM/Sub-Store ***@***.***>
Cc: Feng ***@***.***>, Author ***@***.***>
Subject: Re: [Peng-YM/Sub-Store] 关于clash profile里的trojan节点转换为surge profile - sni未能正确转换 (Issue #73)

能提供一段配置截图吗，关键信息脱敏即可？

  *   原始 Clash 配置截图
  *   转换后 Surge 配置截图

―
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPeng-YM%2FSub-Store%2Fissues%2F73%23issuecomment-1033279387&data=04%7C01%7C%7C657a96496ac24f9bb00108d9eb7417af%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637799706146597775%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=RW5F5efSfTd%2BLLb0MN6ERtTEih8u%2BXMeX4cZm23cPhQ%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAIRZIPUEZVBCHFQ2DAIB33TU2HGTBANCNFSM5N4F5LIQ&data=04%7C01%7C%7C657a96496ac24f9bb00108d9eb7417af%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637799706146597775%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=pjjj5oDoked0tQMDssKjNe4vmUkrI4TqeAMrF5q0qjE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C657a96496ac24f9bb00108d9eb7417af%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637799706146597775%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=SX%2BuTeTKN1OpkgtT%2B8laMrWye1xGMM%2BC8WEm7oXmRSI%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C657a96496ac24f9bb00108d9eb7417af%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637799706146597775%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=9U8KVZu%2BGSv7kG%2FTuJFh5U6JI7AGaHVHTqUGeXrFDSE%3D&reserved=0>.

**Comment by Peng-YM** [comment]
请勿直接回复 GitHub 邮件，附件信息是无法显示出来的:)

**Comment by sanziliu** [comment]
> 请勿直接回复 GitHub 邮件，附件信息是无法显示出来的:)

我在网页端再回复一下。多谢！

![surge](https://user-images.githubusercontent.com/35886142/153111950-f8230d70-797e-4f9f-9f71-5dfd6b7ba0b6.jpg)
![clash](https://user-images.githubusercontent.com/35886142/153111956-71e41fa6-3974-40dd-afff-d775ebff709e.jpg)

**Comment by Peng-YM** [comment]
感谢报告，我会尽快处理这个 issue

**Comment by sanziliu** [comment]
> 感谢报告，我会尽快处理这个 issue

谢谢！

**Comment by Peng-YM** [comment]
抱歉，看了半天代码没有发现问题出在哪里。自己写了一份 Clash 配置也可以正常解析。能否提供一份配置供 Debug 呢？可以用编辑器把重要的信息都替换掉。

**Comment by sanziliu** [comment]
> 抱歉，看了半天代码没有发现问题出在哪里。自己写了一份 Clash 配置也可以正常解析。能否提供一份配置供 Debug 呢？可以用编辑器把重要的信息都替换掉。

你好，我附上了一份sample，转换至surge格式后，sni信息就丢失了。thanks

port: 7890
socks-port: 7891
allow-lan: false
mode: Rule
log-level: info
external-controller: '0.0.0.0:9090'
secret: ''
proxies:
    - { name: 'TJ HK Detour 01', type: trojan, server: tj-hk-01.*****.org, port: 15631, password: *****-56cb-4b10-9544-*****, sni: news.*****.com }
    - { name: 'TJ TW Detour 01', type: trojan, server: tj-tw-01.*****.org, port: 15671, password: *****-56cb-4b10-9544-*****, sni: news.*****.com }
    - { name: 'TJ TW Detour 02', type: trojan, server: tj-tw-02.*****.org, port: 15672, password: *****-56cb-4b10-9544-*****, sni: news.*****.com }
    - { name: 'TJ US Detour 01', type: trojan, server: tj-us-01.*****.org, port: 15651, password: *****-56cb-4b10-9544-*****, sni: news.*****.com }
proxy-groups:
    - { name: auto, type: url-test, proxies: ['TJ HK Detour 01', 'TJ TW Detour 01', 'TJ TW Detour 02', 'TJ US Detour 01'], url: 'https://www.bing.com', interval: 300 }
    - { name: fallback-auto, type: fallback, proxies: ['TJ HK Detour 01', 'TJ TW Detour 01', 'TJ TW Detour 02', 'TJ US Detour 01'], url: 'https://www.bing.com', interval: 300 }
    - { name: select, type: select, proxies: ['TJ HK Detour 01', 'TJ TW Detour 01', 'TJ TW Detour 02', 'TJ US Detour 01'] }
rules:
    - 'IP-CIDR,91.108.56.0/22,select'
    - 'IP-CIDR,91.108.4.0/22,select'
    - 'IP-CIDR,91.108.8.0/22,select'
    - 'IP-CIDR,109.239.140.0/24,select'
    - 'IP-CIDR,149.154.160.0/20,select'
    - 'IP-CIDR,149.154.164.0/22,select'
    - 'DOMAIN-SUFFIX,local,DIRECT'
    - 'IP-CIDR,127.0.0.0/8,DIRECT'
    - 'IP-CIDR,172.16.0.0/12,DIRECT'
    - 'IP-CIDR,192.168.0.0/16,DIRECT'
    - 'IP-CIDR,10.0.0.0/8,DIRECT'
    - 'IP-CIDR,17.0.0.0/8,DIRECT'
    - 'IP-CIDR,100.64.0.0/10,DIRECT'
    - 'GEOIP,CN,DIRECT'
    - 'MATCH,select'

**Comment by Peng-YM** [comment]
我发现了问题所在，你这个 Clash 配置格式是有问题的。
```yaml
- { name: 'TJ HK Detour 01', type: trojan, server: tj-hk-01.xxxxx.org, port: 15631, password: xxxxx, sni: news.xxxxx.com }
```

这里 `type`, `server`, `password`, `sni` 字段都需要加上引号，不然不符合 JSON 格式的要求，导致无法解析，例如：
```
- { name: 'TJ HK Detour 01', type: 'trojan', server: 'tj-hk-01.xxxxx.org', port: 15631, password: 'xxxxx', sni: 'news.xxxxx.com' }
```

**Comment by sanziliu** [comment]
多谢
