### ISSUE TITLE
无法创建订阅是什么问题

### ISSUE THREAD

**Issue by lxtx528** [Peng-YM/Sub-Store#75]
sub-store无法配置订阅该怎么操作？提示无法获取网络环境,创建时提示发生错误，无法创建订阅。

**Comment by Peng-YM** [comment]
应该是没有配置好，请参考 Surge、Loon、QX 各自的教程配置好再创建订阅

**Comment by lxtx528** [comment]
收到，我在尝试一下，谢谢。

Peng-YM ***@***.***>于2022年3月11日 周五21:10写道：
