### ISSUE TITLE
vmess节点的加密类型被改成none

### ISSUE THREAD

**Issue by EpiphanyCat** [Peng-YM/Sub-Store#78]
转换后加密类型被强制转换成了none，patch和tls-name也没保留下来

**Comment by Peng-YM** [comment]
感谢反馈，能否提供更详细的说明呢？

**Comment by EpiphanyCat** [comment]
> 感谢反馈，能否提供更详细的说明呢？

原订阅链接的节点信息如下（从loon复制）：

中国 呼和浩特bgp 100Mbit = vmess,0.0.0.0,80,chacha20-ietf-poly1305,"xx-xx-xx-xx-xx",transport=ws,alertId=0,path=/api?ed=2048,host=pull.free.video.10010.com,tls-name=pull.free.video.10010.com

经过Sub-Store转换后：

中国 呼和浩特bgp 100Mbit = vmess,0.0.0.0,80,none,"xx-xx-xx-xx-xx",transport=ws,alertId=0,host=pull.free.video.10010.com

加密类型由chacha20-ietf-poly1305改为了none，并缺少了path和tls-name，缺少path导致节点连接失败

**Comment by Peng-YM** [comment]
请提供原始订阅的节点信息（私密信息可以进行替换），Loon 可能会对节点进行处理，这样无法判断是哪里出了问题

**Comment by Peng-YM** [comment]
我已经下载了订阅文件，请尽快修改一下订阅

**Comment by EpiphanyCat** [comment]
> 我已经下载了订阅文件，请尽快修改一下订阅

请问下找到问题了吗

**Comment by Peng-YM** [comment]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/21050064/163296549-af10a19a-0b8e-4229-8fcb-a93c503c6fcc.png">
抱歉前几天实在是太忙了，刚刚看了你之前提供的订阅。发现这个订阅链接本身就没有提供加密方法和 tls name，Sub-Store 解析并没有问题

**Comment by EpiphanyCat** [comment]
> <img alt="image" width="960" src="https://user-images.githubusercontent.com/21050064/163296549-af10a19a-0b8e-4229-8fcb-a93c503c6fcc.png">
> 
> 抱歉前几天实在是太忙了，刚刚看了你之前提供的订阅。发现这个订阅链接本身就没有提供加密方法和 tls name，Sub-Store 解析并没有问题

但确实是缺少了path，没有原来的path路径某个节点是连接不上的

**Comment by Peng-YM** [comment]
> > <img alt="image" width="960" src="https://user-images.githubusercontent.com/21050064/163296549-af10a19a-0b8e-4229-8fcb-a93c503c6fcc.png">
> > 抱歉前几天实在是太忙了，刚刚看了你之前提供的订阅。发现这个订阅链接本身就没有提供加密方法和 tls name，Sub-Store 解析并没有问题
> 
> 但确实是缺少了 path，没有原来的 path 路径某个节点是连接不上的

<img width="1308" alt="image" src="https://user-images.githubusercontent.com/21050064/163302031-9dab0ea9-6200-4bce-a345-1ca5359557aa.png">
Path 识别出来了呀

**Comment by Peng-YM** [comment]
对于加密方式的问题，你可以用脚本操作修改
```js
function operator(proxies) {
    proxies.forEach(p => {
        p.cipher = "chacha20-ietf-poly1305";
    });
}
```

**Comment by EpiphanyCat** [comment]
> > > <img alt="image" width="960" src="https://user-images.githubusercontent.com/21050064/163296549-af10a19a-0b8e-4229-8fcb-a93c503c6fcc.png">
> > > 抱歉前几天实在是太忙了，刚刚看了你之前提供的订阅。发现这个订阅链接本身就没有提供加密方法和 tls name，Sub-Store 解析并没有问题
> > 
> > 
> > 但确实是缺少了 path，没有原来的 path 路径某个节点是连接不上的
> 
> <img alt="image" width="1308" src="https://user-images.githubusercontent.com/21050064/163302031-9dab0ea9-6200-4bce-a345-1ca5359557aa.png">
> 
> Path 识别出来了呀

![666A14D4-316D-4E01-BAB1-BA7DDA0EA8B1](https://user-images.githubusercontent.com/59417283/163303001-b3d4fd52-4f15-40bb-abb3-186ad96dd71c.jpeg)
![0C0BB6FD-2608-4525-99F1-3F0E4284DA44](https://user-images.githubusercontent.com/59417283/163303011-388d26bb-b203-488d-8ee0-08aa4d9c4941.jpeg)
和参数的顺序有关吗？我可能要去咨询loon的开发者

**Comment by Peng-YM** [comment]
你可以在 Safari 访问 sub-store 出来的链接，例如：

https://sub.store/download/TEST?target=Loon

**Comment by EpiphanyCat** [comment]
> 你可以在 Safari 访问 sub-store 生成的链接，例如：
> 
> https://sub.store/download/TEST?target=Loon
> 
> 然后检查是否正确解析到了 `path` 字段

好的，谢谢

**Comment by LimeAroma** [comment]
原订阅链接的节点信息如下（从loon复制）：

中国 呼和浩特bgp 100Mbit = vmess,0.0.0.0,80,chacha20-ietf-poly1305,"xx-xx-xx-xx-xx",transport=ws,alertId=0,path=/api?ed=2048,host=pull.free.video.10010.com,tls-name=pull.free.video.10010.com

经过Sub-Store转换后：

中国 呼和浩特bgp 100Mbit = vmess,0.0.0.0,80,none,"xx-xx-xx-xx-xx",transport=ws,alertId=0,host=pull.free.video.10010.com

加密类型由chacha20-ietf-poly1305改为了none，并缺少了path和tls-name，缺少path导致节点连接失败

Epiphany
