### ISSUE TITLE
When converting from another form to Quantumul X, the default method value is none (type vmess)

### ISSUE THREAD

**Issue by kingsman1112** [Peng-YM/Sub-Store#79]
When I convert another form to Quantumult X form, it makes the parameter value in node become method=none, it makes the button inactive, so it must be method=chacha20-ietf-poly1305 for it to work  motion
Can Sub-Store change parameter values ​​on buttons located in the subscription link?
for example I use Quantumult X then I want to change the value of method=none to method=chacha20-ietf-poly1305 or obfs-host=abc to obfs-host=xyz ?

**Comment by Peng-YM** [comment]
I don't quite understand your description. What did you mean by "it makes the button inactive"?

**Comment by kingsman1112** [comment]
method=none in type vmess the server will not work

**Comment by kingsman1112** [comment]
yes big man

**Comment by kingsman1112** [comment]
i have read the issue before and the error i am describing in the first paragraph is the same as the problem: vmess none # 78 created by EpiphanyCat

**Comment by Peng-YM** [comment]
Could you provide an example that can reproduce this issue? You can copy one node from the original subscription.

**Comment by kingsman1112** [comment]
Initially the node is the form of Shadowrocket, V2ray, Clash, ... If linking with the Sub-Store to convert directly to the form of Quantumult X, the node in the registration link will be defaulted to the encryption parameter value of  no such (method=none) makes the node inactive.
If it was originally a form of Quantumult X, then the registration link is normal because the encryption method has an encrypted value parameter, the encryption method is no longer empty.
I think the admin just need to give the option to specify the encoding type or not for the encrypted value (method=...)
Can admin add the option to change the node's value parameter in the initial link?  For example change the value of obfs-host of the original link from obfs-host=abc then I want to change it to obfs-host=xyz

**Comment by Peng-YM** [comment]
You can always change any attributes of a node by using the Script Operator (“脚本操作”)。
For example, change the encryption to "chacha20-ietf-poly1305":
```js
proxies.forEach(p => {
    p.cipher = "chacha20-ietf-poly1305";
});
```

**Comment by kingsman1112** [comment]
Do you have a website that introduces script operators?
I want to see an example of changing obfs-host

**Comment by Peng-YM** [comment]
Unfortunately, there is no documentation at the moment :(.
If you want to change the `obfs-host` for VMess WebSocket, we can use the following:

```js
function operator(proxies) {
    proxies.forEach(proxy => {
        proxy.sni = "xyz";
    });
}
```

**Comment by kingsman1112** [comment]
i tried it before but it didn't work, obfs-host didn't change

**Comment by Peng-YM** [comment]
> i tried it before but it didn't work, obfs-host didn't change

Could you please provide a screenshot? A kind reminder, you should not use the `link` mode for the Script Operator.

**Comment by kingsman1112** [comment]
![B9F4A68F-6ED6-43EF-B600-C16E347C70C1](https://user-images.githubusercontent.com/94741636/163400734-8c17aac7-0178-4ce9-8701-25ec58f8797c.png)

**Comment by kingsman1112** [comment]
![1E5D6035-14B6-4869-9B0D-9E7F09D7DE02](https://user-images.githubusercontent.com/94741636/163400862-25ae92fd-8486-43b7-9b6a-20face582f1d.png)

**Comment by Peng-YM** [comment]
Try this instead:
```js
function operator(proxies){
    proxies.forEach(proxies => {
        proxies["ws-opts"] = proxies["ws-opts"] | {"headers": {}};
        proxies["ws-opts"].headers = {
                "Host": "abc"
        };
    });
}
```

**Comment by kingsman1112** [comment]
Error updating registration link in Quantumult X: “Response invalid”

**Comment by Peng-YM** [comment]
Sorry I made a mistake, please try the modified code above.

**Comment by kingsman1112** [comment]
still error
![48F5571C-704E-46E6-AB6F-D88A1292460E](https://user-images.githubusercontent.com/94741636/163581481-9ee8f326-3413-4854-b681-9ab11d4edcaf.png)

**Comment by kingsman1112** [comment]
Hello
