### ISSUE TITLE
substore不能正确转换vmess下的tcp和http

### ISSUE THREAD

**Issue by XmdChmd** [Peng-YM/Sub-Store#80]
不能正确转换此类似的节点，正常情况下的节点在圈x中是这样的
vmess=xyzz:8080, method=aes-128-gcm, password=3213123131, obfs=http, obfs-uri=/, fast-open=false, udp-relay=false, aead=true, tag=hhh
但是转换之后是这样的
vmess=xyzz:8080, method=aes-128-gcm, password=3213123131, fast-open=false, udp-relay=false, aead=true, tag=abcd

意思就是将obfs=http这个信息转换丢失，或者是不能进行转换该信息

![W3`$U0SU7)C3$0OIG{9ZUZK](https://user-images.githubusercontent.com/89844802/164859956-13f1709f-c610-47d0-bcdb-d35c5bf87a68.png)

**Comment by Peng-YM** [comment]
麻烦提供一下原始订阅的格式供排查问题~

**Comment by XmdChmd** [comment]
https://ml.hcnmb.cn/api/v1/client/subscribe?token=a0fc33fa369fb9e2367c972353759b39

**Comment by XmdChmd** [comment]
> 麻烦提供一下原始订阅的格式供排查问题~

https://ml.hcnmb.cn/api/v1/client/subscribe?token=a0fc33fa369fb9e2367c972353759b39

**Comment by XmdChmd** [comment]
> 麻烦提供一下原始订阅的格式供排查问题~

我可以删除了吗

**Comment by Peng-YM** [comment]
已下载~

**Comment by Peng-YM** [comment]
据我所知，Vmess 协议的 http 和 tcp 混淆都没有被 QX，Loon，Surge 等支持。

**Comment by XmdChmd** [comment]
> 



> 据我所知，Vmess 协议的 http 和 tcp 混淆都没有被 QX，Loon，Surge 等支持。

大佬，当我在win10使用v2rayN的时候在这个伪装域名的地方添加abc.xyz后也能正常导入到quanx中并且能够识别出混淆，还有就是如果不用substore的情况下，我发的那个订阅也是可以正常导入到quanx中使用的，只不过是订阅中的节点部分后host混淆，部分没有host混淆，但是他们无论有没有host混淆只要在其他设备能用的情况下quanx都能正常使用。总体的来说也就是无论订阅中的tcp，http无论有没有host混淆，只在圈x中通过订阅导入节点，那么这个节点是能够使用的。但是如果通过substore进行转换后，就不能使用了。

**Comment by Peng-YM** [comment]
请试一下打开 VMess AEAD 选项

**Comment by XmdChmd** [comment]
> 

大佬您看下图片，这个图前面那个配置是substore普通转换后的，第二个配置是直接用quanx解析器的
![Uploading 1.png…]()

**Comment by Peng-YM** [comment]
> > 
> 
> 大佬您看下图片，这个图前面那个配置是substore普通转换后的，第二个配置是直接用quanx解析器的 <img alt="1" width="319" src="https://user-images.githubusercontent.com/89844802/165450367-458115e9-1843-4125-91b5-4e3992ea660e.png">

这看上去不是同一个节点呀

**Comment by XmdChmd** [comment]
这个是转换后的区别，一个是订阅直接导入，一个是substore进行普通模式转换。substore转换后只有vmess下的tcp不能用，其他几乎正常
<img width="298" alt="1" src="https://user-images.githubusercontent.com/89844802/165450625-434f1224-671a-46f4-9b71-bf55949d8fc3.png">

**Comment by XmdChmd** [comment]
> 


> > > 
> > 
> > 
> > 大佬您看下图片，这个图前面那个配置是substore普通转换后的，第二个配置是直接用quanx解析器的 <img alt="1" width="319" src="https://user-images.githubusercontent.com/89844802/165450367-458115e9-1843-4125-91b5-4e3992ea660e.png">
> 
> 这看上去不是同一个节点呀

不好意思刚刚没更新订阅更新后如下。订阅也都是从圈x分享到tg上面的，默认是开启aead，并且关闭后节点都会通信失败
<img width="320" alt="1" src="https://user-images.githubusercontent.com/89844802/165452445-151255fe-94a3-4c88-bfbd-952d95caa584.png">
<img width="326" alt="2" src="https://user-images.githubusercontent.com/89844802/165452454-d3f3dcf3-864b-41b8-b5f1-60b50381f822.png">

**Comment by Peng-YM** [comment]
好的，vmess http是最近加入内核的，后续统一处理一下~

**Comment by XmdChmd** [comment]
> 好的，vmess http是最近加入内核的，后续统一处理一下~

麻烦大佬了 如需要节点订阅啥的 回信，我就会提供

**Comment by Peng-YM** [comment]
不用哈~

**Comment by Peng-YM** [comment]
最新版已解决此问题
