### ISSUE TITLE
[建议] 能否增加订阅导出导入功能？

### ISSUE THREAD

**Issue by Soizzer** [Peng-YM/Sub-Store#81]
Sub-store在作为代理工具的辅助工具来说，是一个必不可少的增强工具，非常好用，
我现在Surge、Loon都在使用。
但在切换代理工具时感到一个不方便的地方，
就是不同代理工具导入相同的订阅时，
需要重新设置Sub-store的订阅各项参数，
尤其正则重命名，如果修改的地方多，
都要一一重新设置一遍。

我就想作者是否可以加入一个订阅导出功能？
比如在Surge里设置好的订阅，导出备份，
在切换到Loon的时候，
可以有一个导入在Surge里导出的订阅备份的功能？

**Comment by Peng-YM** [comment]
Sub-Store 已经提供了设置的同步，只需要配置好 GitHub Token 即可在不同的平台进行配置同步。
