### ISSUE TITLE
佬 能支持一下小火箭吗

### ISSUE THREAD

**Issue by JOJOforshaun** [Peng-YM/Sub-Store#82]
小火箭作者说
“sub store针对 User-Agent 返回不同的格式。并没有针对 Shadowrocket 的名字返回相应的格式，建议返回 Clash 格式。”
如果支持小火箭的json格式太麻烦的话，可以考虑针对shadowrocket的UA返回clash格式，因为小火箭基本兼容clash的配置。

**Comment by Peng-YM** [comment]
我尚未验证过新版小火箭能否兼容 Sub-Store，以前的版本是无法启动的。

**Comment by JOJOforshaun** [comment]
> 我尚未验证过新版小火箭能否兼容 Sub-Store，以前的版本是无法启动的。

现在没有问题了，前面的问题都解决了，就剩这一个了。小火箭作者现在给的临时解决方案是在sub store生成的订阅链接后加上?target=Clash就可以正常获取订阅了

**Comment by Peng-YM** [comment]
好的，方便提供一下小火箭的UA吗

**Comment by JOJOforshaun** [comment]
> 好的，方便提供一下小火箭的UA吗

我已经发邮件问了，但是佬还没有回复我

**Comment by Peng-YM** [comment]
> > 好的，方便提供一下小火箭的UA吗
> 
> 我已经发邮件问了，但是佬还没有回复我

好的，这个改动应该非常容易

**Comment by JOJOforshaun** [comment]
> > > 好的，方便提供一下小火箭的UA吗
> > 
> > 
> > 我已经发邮件问了，但是佬还没有回复我
> 
> 好的，这个改动应该非常容易

或许可以先看看我抓的？

不带target=clash时
User-Agent: Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US) AppleWebKit/533.20.25 (KHTML, like Gecko) Version/5.0.4 Safari/533.20.27

带clash时
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:40.0) Gecko/20100101 Firefox/44.0

是这玩意吗

**Comment by Peng-YM** [comment]
> > > > 好的，方便提供一下小火箭的UA吗
> > > 
> > > 
> > > 我已经发邮件问了，但是佬还没有回复我
> > 
> > 
> > 好的，这个改动应该非常容易
> 
> 或许可以先看看我抓的？
> 
> 不带target=clash时 User-Agent: Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US) AppleWebKit/533.20.25 (KHTML, like Gecko) Version/5.0.4 Safari/533.20.27
> 
> 带clash时 User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:40.0) Gecko/20100101 Firefox/44.0
> 
> 是这玩意吗

不是这个，要有可识别的 Shadowrocket UA，你上面的是 Safari 和 Firefox 的 UA

**Comment by JOJOforshaun** [comment]
> > > > > 好的，方便提供一下小火箭的UA吗
> > > > 
> > > > 
> > > > 我已经发邮件问了，但是佬还没有回复我
> > > 
> > > 
> > > 好的，这个改动应该非常容易
> > 
> > 
> > 或许可以先看看我抓的？
> > 不带target=clash时 User-Agent: Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US) AppleWebKit/533.20.25 (KHTML, like Gecko) Version/5.0.4 Safari/533.20.27
> > 带clash时 User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:40.0) Gecko/20100101 Firefox/44.0
> > 是这玩意吗
> 
> 不是这个，要有可识别的 Shadowrocket UA，你上面的是 Safari 和 Firefox 的 UA

小火箭回复
Shadowrocket的 User-Agent 就是Shadowrocket，但是如果用户在Shadowrocket开启了“隐藏我的用户代理”，将使用Safari的。

**Comment by Peng-YM** [comment]
已支持
