### ISSUE TITLE
随机出现报错：云配置同步失败

### ISSUE THREAD

**Issue by vernesong** [Peng-YM/Sub-Store#86]
![IMG_0552](https://user-images.githubusercontent.com/42875168/167610381-4b80ca7a-d585-45a4-afb2-435169a677a7.PNG)
这个弹窗报错出现频率很高，有时是一个，有时是多个，而且组合订阅中经常只包含其中一个订阅的节点，能否加入失败重试的处理方式

**Comment by Peng-YM** [comment]
请问是否更新到最新版？最新版应该已经修复了这个问题

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/167612995-b6a7e941-1d9c-4882-b289-105e2a3bf9b5.jpeg)
![image](https://user-images.githubusercontent.com/42875168/167613066-156d57a8-2ddc-45f3-b662-dfdd5afd5209.png)

还是很频繁

**Comment by Peng-YM** [comment]
emmmm，这个问题有点难缠，有时间会处理的

**Comment by Peng-YM** [comment]
看你这个报的错误是请求超时，而且我自己尝试了几次没有出现这种情况，请排查一下网络问题

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/167615900-712901a1-27c7-4e2b-b766-9a2c5b1ca717.png)
这个错误比较常见其实，还有就是有时候组合订阅只包含其中一个订阅的节点就上传了，这个能不能修改下，节点获取失败就跳过上传

**Comment by Peng-YM** [comment]
> 

所以问题的原因是组合订阅中的某个子订阅出了问题么？

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/168197894-ddfeec51-790f-4ab6-84a0-5fcd0b870b96.png)
还是一样容易丢节点
