### ISSUE TITLE
对脚本处理添加URL参数支持

### ISSUE THREAD

**Issue by qwerzl** [Peng-YM/Sub-Store#90]
您好，

请问脚本处理是否可以加入对URL arguments的支持（类似Surge中的$arguments）？

**Comment by Peng-YM** [comment]
目前没有这种打算，我对这个需求表示怀疑。Sub-Store 的设计目标就是尽量减少URL参数以降低配置难度

**Comment by qwerzl** [comment]
主要是...最近写了个sub-store脚本，想要满足更多人需求，不得不写了很多variants，其实都没什么区别。如果没有arguments支持的话真的会麻烦很多。

**Comment by Peng-YM** [comment]
你指的是sub-store里面脚本链接用URL参数形式传递吗？我之前好像理解错了

**Comment by Peng-YM** [comment]
这个是可以做的，我之后加一下

**Comment by qwerzl** [comment]
感谢~

**Comment by Peng-YM** [comment]
请参考 [TLS 指纹脚本操作](https://raw.githubusercontent.com/Peng-YM/Sub-Store/6bb837f74fcd0933c203e939060b66508d2ac7ae/scripts/tls-fingerprint.js)

**Comment by Peng-YM** [comment]
例如脚本链接是  https://xxx.com/yyy.js#a=1&b，则脚本操作里面可以引用如下变量：
```js
$arguments = {
    "a": "1",
    "b": true
};
```

**Comment by nichwang88** [comment]
一个设想不知是否能实现：把几个常用机场的指纹定义在脚本里，在url里添加指定机场名称(指向指纹)。如有指纹更新，直接在脚本里更新即可。
