### ISSUE TITLE
订阅页面订阅列表旁边不显示弹出菜单按钮了

### ISSUE THREAD

**Issue by Soizzer** [Peng-YM/Sub-Store#92]
订阅页面订阅列表旁边不显示弹出菜单按钮了，现在想编辑订阅，只能在大概位置点击才行，而没有明显的图标显示应点击的区域。

以前这个位置我记得是显示有3个小点点的。

![030C6D4A-FCB3-4D6D-897E-5B7BDDD425B2](https://user-images.githubusercontent.com/73036854/169189146-6908fed3-1d2f-4f3e-a1a6-47b7e4018dd0.jpeg)

**Comment by Peng-YM** [comment]
![IMG_3468](https://user-images.githubusercontent.com/21050064/169191114-22a18eb7-c477-4209-a69c-26cca88ae745.jpg)

我是没有问题的哦

**Comment by Soizzer** [comment]
> ![IMG_3468](https://user-images.githubusercontent.com/21050064/169191114-22a18eb7-c477-4209-a69c-26cca88ae745.jpg)
> 
> 我是没有问题的哦

咦？这样啊？
那难道会跟升级了iOS15.5有关吗？
请问你的iOS也是15.5吗？
我的也是升级iOS之后出现的，
我以为是substore更新了界面呢

**Comment by Peng-YM** [comment]
看着像是这个按钮的图表被屏蔽了没加载出来

**Comment by Soizzer** [comment]
> 看着像是这个按钮的图表被屏蔽了没加载出来

那请问该如何处理这种情况呢？
我自己除了试了2部iPhone，又测试了iPad，使用了Surge、Loon，还在不同的浏览器Chrome、Alook和系统自带的Safari浏览器都遇到了一模一样的情况。然后发现在编辑订阅界面的“节点操作”功能，重命名等功能的“确定”按钮和“添加节点操作”按钮都不显示了。

**Comment by Soizzer** [comment]
常用选项的单选按钮也不显示了
如果新建订阅
很多设置将无法成功设定
![87674ADF-AABC-4F44-AD0E-7A7FE2DF077D](https://user-images.githubusercontent.com/73036854/169592112-76d8de29-dd40-4a7c-800a-25c88d5ab631.jpeg)
