### ISSUE TITLE
关于资源解析器版使用问题

### ISSUE THREAD

**Issue by JOJOforshaun** [Peng-YM/Sub-Store#94]
https://raw.githubusercontent.com/Peng-YM/Sub-Store/master/scripts/sub-store-parser.js
这个是否可以像qx的解析器一样在订阅链接后加#参数修改订阅呢？可以的话我打算再跟老李提个建议，让小火箭兼容一下

**Comment by JOJOforshaun** [comment]
好像解析器没兼容一下shadowrocket的ua？
![Uploading 6BC90BD2-C1C2-401F-A32C-9B5E588EEBAD.png…]()

**Comment by Peng-YM** [comment]
嗯解析器版好久没有更新了，有时间更新一下。UA 会支持的，但是目前没有计划支持URL参数，如果有这个需求建议用sub-store

**Comment by Peng-YM** [comment]
Sub-Store解析器已更新，解析能力目前和网页版保持一致

**Comment by Peng-YM** [comment]
如果ShadowRocket跟进这个功能，Sub-Store可以针对性适配
