### ISSUE TITLE
求助，sub-store数据同步提示无法拉取订阅列表

### ISSUE THREAD

**Issue by jesir000** [Peng-YM/Sub-Store#97]
app为圈叉

**Comment by Peng-YM** [comment]
求助的时候需要提供尽可能详细的信息，请至少给出：

- 对应配置
- 日志信息
- 最近请求记录

**Comment by Peng-YM** [comment]
求助前是否已经认真阅读说明并配置好 Sub-Store？

**Comment by jesir000** [comment]
![image](https://user-images.githubusercontent.com/73181101/169508403-ef7ccbf2-f2c9-4b34-a261-5ed3dabb7d01.jpeg)![image](https://user-images.githubusercontent.com/73181101/169508429-28e27985-f769-47d4-8c62-f6149fbe8875.png)![image](https://user-images.githubusercontent.com/73181101/169508441-5041afaf-e3b8-4324-bf01-f3c2faf9a7b5.png)

**Comment by jesir000** [comment]
使用的是圈x重写

**Comment by Peng-YM** [comment]
手动执行这个脚本试试：

https://raw.githubusercontent.com/Peng-YM/Sub-Store/master/scripts/revert.js

我问的是你具体是怎么配置的，你说“圈X重写”能给我提供什么信息呢？

**Comment by jesir000** [comment]
![image](https://user-images.githubusercontent.com/73181101/169514965-81323044-9c02-4d2c-908e-fd6603f34066.png)
执行完脚本后依然提示无法拉取订阅列表，
-具体配置：「ipad，iphone填写用户名和token」-「ipad端上传」-「iphone端恢复」-「无法拉取订阅列表」

**Comment by Peng-YM** [comment]
可能 Token 没有对应权限，你同步配置后有提示同步成功吗？

**Comment by jesir000** [comment]
重新设置token给了所有权限，先提示「同步成功」，紧接着就提示「无法拉取订阅列表」

**Comment by Peng-YM** [comment]
QX 的 bug，其实应该是拉取成功了的。重新打开 QX 应该能看到

**Comment by jesir000** [comment]
看了一下gist备份的内容，实际上没有备份订阅数据![image](https://user-images.githubusercontent.com/73181101/169524939-2754d873-0d63-4561-b6ce-2b1ab7b729c0.jpeg)

**Comment by Peng-YM** [comment]
无足够有效信息判断是什么问题

**Comment by jesir000** [comment]
什么情况会出现已经配置好的订阅消失？刚刚打开sub-store发现订阅没了。
期间有重启过圈叉，更换过token
![image](https://user-images.githubusercontent.com/73181101/169544969-15cddab8-9797-4d5f-9c7d-51595e055edb.png)

**Comment by Peng-YM** [comment]
除非清理了缓存，否则订阅不会消失。是否在其他软件里配置的sub-store？

**Comment by jesir000** [comment]
没有在其他软件配置过。
至于缓存应该没有清理过，因为我不知道怎么清理😂

**Comment by Peng-YM** [comment]
建议卸载QX重新配置Sub-Store，我确定这是你的问题
