### ISSUE TITLE
转换旗帜

### ISSUE THREAD

**Issue by Marsoit** [Peng-YM/Sub-Store#99]
我有个疑问，就是在转换显示国家与地区旗帜emoji之后，台湾地区的旗帜为什么会解析成大陆的国旗，我看过源码也是正确写成地区的旗帜emoji，还有就是能否用正则排除俄罗斯国旗emoji中白俄罗斯，以正确显示白俄罗斯的国旗，当然这些其实也是无关紧要的小问题，只是我个人有点强迫症而已，所以想请教一下原因，以从中学习经验，如有冒犯之处，请见谅

**Comment by Peng-YM** [comment]
台湾地区的旗帜在大多数 Sub-Store 用户的手机上无法正确显示，因此统一用中国国旗代替

**Comment by Marsoit** [comment]
了解

**Comment by Peng-YM** [comment]
白俄罗斯的国旗有时间我处理一下~
